# Generated by Django 5.1.2 on 2024-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BA_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='writers', to='BA_app.book'),
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='One Author has many books, many books has one Author.'),
            preserve_default=False,
        ),
    ]
